"""Focused live-analysis regressions over genuinely generated bytes."""

from __future__ import annotations

import io
import json
import time
import warnings
import zipfile
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from docx import Document
from PIL import Image

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    from fastapi.testclient import TestClient

from dalel.api.app import create_app
from dalel.api.live import reset_live_jobs
from dalel.api.visual_triage import build_visual_inventory


@pytest.fixture(scope="module")
def client() -> Iterator[TestClient]:
    reset_live_jobs()
    value = TestClient(create_app())
    yield value
    reset_live_jobs()


def _docx_bytes() -> bytes:
    document = Document()
    document.add_heading("Общие сведения", level=1)
    document.add_paragraph(
        "Новый тестовый проект расположен в Кызылординской области. "
        "Площадь участка составляет 12,5 га."
    )
    document.add_heading("Охрана окружающей среды", level=1)
    document.add_paragraph(
        "Объем выбросов составляет 10 тонн в год. Плановый объем составляет 12 тонн в год."
    )
    table = document.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "Показатель"
    table.cell(0, 1).text = "Значение"
    table.cell(1, 0).text = "Площадь"
    table.cell(1, 1).text = "12,5 га"
    output = io.BytesIO()
    document.save(output)
    return output.getvalue()


def _request(section_id: str, upload_indices: list[int]) -> dict[str, Any]:
    return {
        "mode": "live_analysis",
        "project_display_name": "Новый синтетический проект",
        "sections": [{"section_id": section_id, "upload_indices": upload_indices}],
    }


def _poll(client: TestClient, created: dict[str, Any]) -> dict[str, Any]:
    token = str(created["access_token"])
    headers = {"X-Dalel-Job-Token": token}
    current = created
    for _ in range(200):
        if current["status"] in {"completed", "failed", "cancelled"}:
            return current
        time.sleep(0.025)
        current = client.get(f"/api/live/jobs/{created['job_id']}", headers=headers).json()
    pytest.fail("live job did not reach a terminal state")


def test_new_docx_runs_real_job_local_pillars_and_requires_token(
    client: TestClient,
) -> None:
    payload = _docx_bytes()
    request = _request("project_documents", [0, 1])
    response = client.post(
        "/api/live/jobs",
        data={"request": json.dumps(request, ensure_ascii=False)},
        files=[
            (
                "files",
                (
                    "new-project.docx",
                    payload,
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                ),
            ),
            (
                "files",
                (
                    "same-bytes.docx",
                    payload,
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                ),
            ),
        ],
    )
    assert response.status_code == 202
    created = response.json()
    assert created["job_id"].startswith("live_")
    assert len(created["access_token"]) >= 40
    assert created["files"][1]["duplicate_of"] == created["files"][0]["file_id"]

    job_path = f"/api/live/jobs/{created['job_id']}"
    assert client.get(job_path).status_code == 404
    assert client.get(job_path, headers={"X-Dalel-Job-Token": "incorrect-token"}).status_code == 404

    completed = _poll(client, created)
    assert completed["status"] == "completed"
    assert completed["progress"] == 100
    assert "access_token" not in completed
    result = completed["result"]
    assert result["mode"] == "live_analysis"
    assert result["project_id"] != "project_003_bayterek"
    assert "project_003_bayterek" not in json.dumps(result, ensure_ascii=False)
    assert result["preparation"]["document_count"] == 1
    assert result["preparation"]["prepared_document_count"] == 1
    assert result["preparation"]["page_count"] >= 1
    assert result["inventory"]["duplicate_files"] == [created["files"][1]["file_id"]]
    assert result["pillars"]["P1"]["status"] == "completed"
    assert result["pillars"]["P3"]["status"] == "completed"
    assert result["pillars"]["P4"]["status"] == "insufficient_input"
    assert result["meta"]["project_id"] == result["project_id"]
    assert result["meta"]["calibrated_probability"] is None
    assert result["meta"]["shap_contributions"] is None

    events = client.get(
        f"{job_path}/events",
        headers={"X-Dalel-Job-Token": created["access_token"]},
    ).json()["events"]
    states = [item["state"] for item in events]
    assert states[-1] == "completed"
    assert "running_p1" in states
    assert "running_meta" in states


def test_zip_is_extracted_and_supporting_only_job_has_no_meta(
    client: TestClient,
) -> None:
    archive_bytes = io.BytesIO()
    with zipfile.ZipFile(archive_bytes, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("hearing/protocol.docx", _docx_bytes())
    response = client.post(
        "/api/live/jobs",
        data={"request": json.dumps(_request("hearing_protocol", [0]))},
        files=[("files", ("protocols.zip", archive_bytes.getvalue(), "application/zip"))],
    )
    assert response.status_code == 202
    completed = _poll(client, response.json())
    assert completed["status"] == "completed"
    assert completed["files"][0]["archive_status"] == "extracted"
    result = completed["result"]
    assert result["archive_updates"][completed["files"][0]["file_id"]] == {
        "archive_status": "extracted"
    }
    extracted = [
        item
        for item in result["inventory"]["files"]
        if item["source_origin"] == "extracted_archive"
    ]
    assert len(extracted) == 1
    assert result["preparation"]["prepared_document_count"] == 1
    assert result["preparation"]["model_input_document_count"] == 0
    assert result["meta"] is None
    assert all(result["pillars"][pillar]["status"] == "unavailable" for pillar in result["pillars"])


def test_live_intake_rejects_zero_bytes_mime_mismatch_and_zip_traversal(
    client: TestClient,
) -> None:
    request = json.dumps(_request("project_documents", [0]))
    zero = client.post(
        "/api/live/jobs",
        data={"request": request},
        files=[("files", ("empty.pdf", b"", "application/pdf"))],
    )
    assert zero.status_code == 422
    assert zero.json()["error"] == "empty_file"

    wrong_mime = client.post(
        "/api/live/jobs",
        data={"request": request},
        files=[("files", ("project.pdf", b"%PDF-1.4\n%%EOF", "image/png"))],
    )
    assert wrong_mime.status_code == 422
    assert wrong_mime.json()["error"] == "mime_mismatch"

    unsafe_archive = io.BytesIO()
    with zipfile.ZipFile(unsafe_archive, "w") as archive:
        archive.writestr("../escape.pdf", b"%PDF-1.4\n%%EOF")
    traversal = client.post(
        "/api/live/jobs",
        data={"request": json.dumps(_request("hearing_protocol", [0]))},
        files=[("files", ("unsafe.zip", unsafe_archive.getvalue(), "application/zip"))],
    )
    assert traversal.status_code == 422
    assert traversal.json()["error"] == "archive_path_traversal"


def _pattern_image(path: Path, *, checkerboard: bool) -> None:
    image = Image.new("RGB", (128, 128))
    for y in range(128):
        for x in range(128):
            if checkerboard:
                value = 30 if (x // 8 + y // 8) % 2 else 220
                image.putpixel((x, y), (value, value, value))
            else:
                image.putpixel((x, y), (x, y, (x + y) % 256))
    image.save(path, format="PNG")


def test_visual_inventory_preserves_provenance_and_separates_procedural_notice(
    tmp_path: Path,
) -> None:
    input_dir = tmp_path / "input"
    input_dir.mkdir()
    visual = input_dir / "visual.png"
    duplicate = input_dir / "duplicate.png"
    notice = input_dir / "notice.png"
    _pattern_image(visual, checkerboard=False)
    duplicate.write_bytes(visual.read_bytes())
    _pattern_image(notice, checkerboard=True)
    inventory = [
        {
            "file_id": "VISUAL_A",
            "section_id": "visual_geographic_materials",
            "display_filename": "site-photo.png",
            "media_type": "png",
            "internal_path": "input/visual.png",
        },
        {
            "file_id": "VISUAL_B",
            "section_id": "visual_geographic_materials",
            "display_filename": "site-photo-copy.png",
            "media_type": "png",
            "internal_path": "input/duplicate.png",
        },
        {
            "file_id": "NOTICE",
            "section_id": "procedural_publication_evidence",
            "display_filename": "hearing-notice.png",
            "media_type": "png",
            "internal_path": "input/notice.png",
        },
    ]
    result = build_visual_inventory(
        tmp_path,
        job_id="live_visual_fixture",
        curated_dir=None,
        inventory=inventory,
    )
    assert result["visual_analysis_status"] == "not_available"
    assert result["geospatial_analysis_status"] == "not_available"
    assert result["exact_or_near_duplicates"] == 1
    records = {item["source_file_id"]: item for item in result["assets"]}
    assert records["NOTICE"]["triage_state"] == "procedural_notice"
    assert records["NOTICE"]["procedural_supporting_evidence"] is True
    assert records["NOTICE"]["eligible_for_future_p5"] is False
    duplicate_records = [item for item in result["assets"] if item["triage_state"] == "duplicate"]
    assert len(duplicate_records) == 1
    assert duplicate_records[0]["duplicate_of_asset_id"] is not None
    assert all(item["visual_analysis_status"] == "not_available" for item in result["assets"])
